version: '3.8'

# Development-specific overrides
services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev_password

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  minio:
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: climacool-prometheus
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - climacool-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: climacool-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - climacool-network
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: