name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '20.x'

jobs:
  backend-build-test:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: climacool_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/backend
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./src/backend
    
    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: ./src/backend
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=climacool_test;Username=test_user;Password=test_password"
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: ./src/backend/coverage

  frontend-customer-portal-build-test:
    name: Customer Portal Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./src/frontend/customer-portal/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./src/frontend/customer-portal
    
    - name: Lint
      run: npm run lint
      working-directory: ./src/frontend/customer-portal
    
    - name: Build
      run: npm run build
      working-directory: ./src/frontend/customer-portal
    
    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: ./src/frontend/customer-portal
      continue-on-error: true

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-customer-portal-build-test]
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: climacool_user
          POSTGRES_PASSWORD: dev_password
          POSTGRES_DB: climacool
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./src/frontend/customer-portal/package-lock.json
    
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef
    
    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./src/frontend/customer-portal
    
    - name: Restore Backend Dependencies
      run: dotnet restore
      working-directory: ./src/backend
    
    - name: Build Backend
      run: dotnet build --no-restore --configuration Release
      working-directory: ./src/backend
    
    - name: Run Database Migrations
      run: dotnet ef database update --project ../ClimaCool.Infrastructure
      working-directory: ./src/backend/ClimaCool.API
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=climacool;Username=climacool_user;Password=dev_password"
    
    - name: Start Backend API
      run: |
        cd src/backend/ClimaCool.API
        nohup dotnet run --environment Development --urls "http://localhost:5000" --no-launch-profile > backend.log 2>&1 &
        echo $! > backend.pid
        sleep 10
        curl http://localhost:5000/health || (cat backend.log && exit 1)
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=climacool;Username=climacool_user;Password=dev_password"
    
    - name: Build Frontend
      run: npm run build
      working-directory: ./src/frontend/customer-portal
    
    - name: Start Frontend
      run: |
        cd src/frontend/customer-portal
        nohup npm start -- --port 4201 > frontend.log 2>&1 &
        echo $! > frontend.pid
        # Wait for frontend to be ready
        for i in {1..30}; do
          if curl -s http://localhost:4201 > /dev/null; then
            echo "Frontend is ready"
            break
          fi
          sleep 2
        done
        curl -I http://localhost:4201 || (cat frontend.log && exit 1)
    
    - name: Run E2E Tests
      run: npx cypress run --headless --browser chrome
      working-directory: ./src/frontend/customer-portal
    
    - name: Stop Services
      if: always()
      run: |
        if [ -f src/backend/ClimaCool.API/backend.pid ]; then
          kill $(cat src/backend/ClimaCool.API/backend.pid) || true
        fi
        if [ -f src/frontend/customer-portal/frontend.pid ]; then
          kill $(cat src/frontend/customer-portal/frontend.pid) || true
        fi
    
    - name: Upload E2E Test Results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-test-results
        path: |
          ./src/frontend/customer-portal/cypress/screenshots
          ./src/frontend/customer-portal/cypress/videos

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-customer-portal-build-test, e2e-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Backend Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/backend
        file: ./src/backend/Dockerfile
        push: false
        tags: climacool-api:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Customer Portal Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./src/frontend/customer-portal
        file: ./src/frontend/customer-portal/Dockerfile
        push: false
        tags: climacool-customer-portal:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # SonarCloud analysis would go here if configured
    # For now, we'll just run basic code analysis
    
    - name: Run .NET Code Analysis
      run: |
        dotnet tool install --global dotnet-format
        dotnet format --verify-no-changes --verbosity diagnostic
      working-directory: ./src/backend
      continue-on-error: true